# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0002_remove_employee_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='em.Employee'),
        ),
    ]
